### ISSUE TITLE
Correct spacing on Download Form screen

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-CivilActionCoverSheet#16]
`Page id: download form`

1. **Turn numbered text on download form screen into numbered list**: Add an empty line before numbers to make the numbered text turn into a numbered list. 

2. **Spacing after make changes button**: Add a whole empty line before submit to court button.

[Discussion in first demo](https://youtu.be/mCBSCt6z2RM?t=3261)

**Comment by LGG233** [comment]
Opened up spacing on `page id: download form`.

**Comment by LGG233** [comment]
Issue resolved.
