### ISSUE TITLE
Take question from basic questions and add conditional language to page id: your address

### ISSUE THREAD

**Issue by LGG233** [SuffolkLITLab/docassemble-CivilActionCoverSheet#22]
`Page id: your address`

Was NOT discussed in First Demo, but we need to find a way to ask "What is your address?" without using "your" since the form is more likely to be filled out by the attorney than the plaintiff. Maybe with similar language to that used in the 209A ("answer the following questions as if you were the plaintiff")? Or maybe using "plaintiff" instead of "you."

**Comment by maevemacglinchey** [comment]
`Page id: your address`

Add conditional language to adjust for whether user is attorney or pro se.

Will read:

Pro se: What is your address?
Attorney: What is your client's address?

**Comment by maevemacglinchey** [comment]
Post-MVP: ask using plaintiff's name in tag `${ }`

**Comment by maevemacglinchey** [comment]
Example from Caroline
interviewee = lawyer or pro se

What is your name?

What is
% if interviewee == pro se:
your
% else:
your client's
% endif
name?

% if interviewee == pro se:
What is your name?
% else:
What is your client's name?
% endif
