### ISSUE TITLE
"Did anyone else file with you?"

### ISSUE THREAD

**Issue by LGG233** [SuffolkLITLab/docassemble-CivilActionCoverSheet#49]
Language doesn't work on `page id: any other users`. It currently reads:

> "Did anyone else file with you?
> We need to know the name of everyone who is part of this case.
> Is anyone else on your side of this case?" 
> 

If an attorney is filling out the form (quite probable with the CACS), the question doesn't work. Maybe it should be something like: "Are there any other plaintiffs?"

**Comment by maevemacglinchey** [comment]
Superseded by issue #51.
