### ISSUE TITLE
Zipcode validator to prevent error in court code

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-CivilActionCoverSheet#50]
1. Determine catchment area for courts covered in these forms
2. Add ZIP code validator to prevent user from adding addresses other than those in MA, as those addresses outside out of MA triggers an error in courts code.

If zipcode doesn't start with xxx, ask 'are you sure...' and not let you continue until that validator.

021xx - 024xx (zipcodes are 5 digits)

**Comment by maevemacglinchey** [comment]
Should we include language to let the user know that they can only enter MA addresses prior to validation?

**Comment by LGG233** [comment]
Validating the zip code is outside of the scope of our form so closing the issue.
