### ISSUE TITLE
SME Check: Can we cite only one plaintiff/defendant in the case where there are two or more?

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-CivilActionCoverSheet#51]
In cases where there are two or more plaintiffs or defendants, can we cite only the first one in the coversheet or is it necessary to include all plaintiffs and defendants?

**Comment by maevemacglinchey** [comment]
More than one plaintiff/defendant, add attachment

**Comment by LGG233** [comment]
According to SME, each Plaintiff needs to file a separate cover sheet which can name several defendants. This issue has been superceded by #107
