### ISSUE TITLE
Rework language on attorney name question

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-CivilActionCoverSheet#84]
Maeve: I wonder if that language could even be finessed even more? 'You are the attorney' was taken from earlier basic questions/209A and I get the argument that it reminds the user that they have selected that they are the attorney but...it just feels clunky (for lack of a better word). Let's see how it goes.

Lance: I agree on the "you are the attorney" language. Can't remember exactly what it says but we probably don't even need that, just something like "Please provide your name (we'll get the name of your client later)" - that's too casual but you get the idea

**Comment by LGG233** [comment]
Fixed in earlier versions.
