### ISSUE TITLE
0 printing to pdf when no checkboxes selected

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-CivilActionCoverSheet#87]
**Preview pdf**
<img width="585" alt="Test 3 preview snip" src="https://user-images.githubusercontent.com/49881041/95789781-6f07fe80-0cde-11eb-9c99-dcc78c8c5380.PNG">
**Final pdf**
<img width="581" alt="Test 3 final snip" src="https://user-images.githubusercontent.com/49881041/95789784-716a5880-0cde-11eb-9047-3fa289c0a322.PNG">

Perhaps we should make nothing print when no checkboxes are selected? Or all 0?

**Comment by LGG233** [comment]
No longer needed.
