### ISSUE TITLE
Review all sections language (possible issue)

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-CivilActionCoverSheet#95]
After all the testing we did, I'm hyper conscious of the language here. As far as I know, there's no standard across the project but from testing, I know we used 'tap'. I think this is something we should bring up in Tactical Tuesday as a point to standardise so I'm flagging it here to remind us to change this accordingly.
![image](https://user-images.githubusercontent.com/49881041/100581238-158c7b00-32f0-11eb-9e7d-18a698ccbbe9.png)

**Comment by LGG233** [comment]
No longer relevant
